apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: my-cluster-ec2
    region: ap-southeast-1

nodeGroups:
    - name: ng-1
      instanceType: t3.small
      desiredCapacity: 1
      ssh:
        publickeyName: the1-cpp
    # - name: ng-mixed
    #   minSize: 3
    #   maxSize: 5
    #   instancesDistribution:
    #         maxPrice: 0.2
    #         instanceTypes: ["t3.small"]
    #         onDemandBaseCapacity: 0
    #         onDemandPercentageAboveBaseCapacity: 50
    #   ssh:
    #     publickeyName: the1-cpp
    - name: ng-stateless-workload
      desiredCapacity: 3
      maxSize: 10
      instancesDistribution:
            instanceTypes: ["t3.small"]
            onDemandBaseCapacity: 0
            onDemandPercentageAboveBaseCapacity: 0
      iam:
            withAddonPolicies:
                autoScaler: true
      labels:
            nodegroup-type: stateless-workload
            instance-type: spot
      ssh: 
            publicKeyName: the1-cpp
cloudWatch:
      clusterLogging:
            enableTypes: ["*"]