apiVersion: v1
kind: Pod
metadata:
    name: rng-with-liveness
spec:
    containers:
        -   name: rng
            image: dockercoins/rng:v0.1
            livenessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 10
                periodSeconds: 1