apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-03-05T08:50:41Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "823537"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web
  uid: ed556734-e85f-4c1d-aaf8-b83ad79ade28
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
