apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"worker"},"name":"worker","namespace":"default"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"worker"}},"template":{"metadata":{"labels":{"app":"worker"}},"spec":{"containers":[{"image":"dockercoins/worker:v0.1","name":"worker"}]}}}}
  creationTimestamp: "2020-01-08T08:47:58Z"
  generation: 3
  labels:
    app: worker-edit
  name: worker-edit
  namespace: default
  resourceVersion: "3611779"
  selfLink: /apis/apps/v1/namespaces/default/deployments/worker
  uid: a06f598d-a401-4a3a-ac8c-ca3e440f9951
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-edit
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker-edit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2020-01-08T08:47:58Z"
    lastUpdateTime: "2020-01-08T08:49:02Z"
    message: ReplicaSet "worker-598788db65" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-15T09:54:28Z"
    lastUpdateTime: "2020-01-15T09:54:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 10
  replicas: 5
  updatedReplicas: 10
